name: CHUNGWI
title: Chungwi's | A blog theme for Chungwi's
description: This is the Chungwi's first Blog 
tags:
  - blog
  - template
  - jekyll
  - theme
  - netlify
show_hero: false
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Feed
    url: /feed.xml
email: dungwi@gmail.com
# disqus_username: disqus_username
paginate : 12
